import { AttributeParams } from '@/utils/component-attributes-table';

export const rowAttributes: AttributeParams[] = [
  {
    name: 'tag',
    description: '-',
    type: 'string',
    required: false,
    defaultValue: 'div',
    possibleValues: '*',
  },
  {
    name: 'gutter',
    description: '-',
    type: 'number',
    required: false,
    defaultValue: '-',
    possibleValues: '*',
  },
  {
    name: 'type',
    description: '-',
    type: 'string',
    required: false,
    defaultValue: '-',
    possibleValues: '*',
  },
  {
    name: 'justify',
    description: '-',
    type: 'string',
    required: false,
    defaultValue: 'start',
    possibleValues: '*',
  },
  {
    name: 'align',
    description: '-',
    type: 'string',
    required: false,
    defaultValue: 'top',
    possibleValues: '*',
  },
];

export const colAttributes: AttributeParams[] = [
  {
    name: 'tag',
    description: '-',
    type: 'string',
    required: false,
    defaultValue: 'div',
    possibleValues: '*',
  },
  {
    name: 'span',
    description: '-',
    type: 'number',
    required: false,
    defaultValue: '24',
    possibleValues: '*',
  },
  {
    name: 'offset',
    description: '-',
    type: 'number',
    required: false,
    defaultValue: '-',
    possibleValues: '*',
  },
  {
    name: 'pull',
    description: '-',
    type: 'number',
    required: false,
    defaultValue: '-',
    possibleValues: '*',
  },
  {
    name: 'push',
    description: '-',
    type: 'number',
    required: false,
    defaultValue: '-',
    possibleValues: '*',
  },
  {
    name: 'xs',
    description: '-',
    type: 'number | object',
    required: false,
    defaultValue: '-',
    possibleValues: '*',
  },
  {
    name: 'sm',
    description: '-',
    type: 'number | object',
    required: false,
    defaultValue: '-',
    possibleValues: '*',
  },
  {
    name: 'md',
    description: '-',
    type: 'number | object',
    required: false,
    defaultValue: '-',
    possibleValues: '*',
  },
  {
    name: 'lg',
    description: '-',
    type: 'number | object',
    required: false,
    defaultValue: '-',
    possibleValues: '*',
  },
  {
    name: 'xl',
    description: '-',
    type: 'number | object',
    required: false,
    defaultValue: '-',
    possibleValues: '*',
  },
];
